server:
  servlet:
    context-path: /api/service-relationship
  port: 6788

keycloak:
  realm: SocialNetworkRealm
  auth-server-url: http://localhost:8080/
  ssl-required: external
  resource: social-network
  use-resource-role-mappings: true
  bearer-only: true
  public-client: true

spring:
  main:
    allow-bean-definition-overriding: true #cho phép việc ghi đè (overriding) các bean trong ứng dụng
  application:
    name: relationship-service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changes/db.changelog-master.xml
    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/db_fb_clone_service_relationship
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: relationship-service
      connection-timeout: 30000 #thời gian tối đa (tính = millisecond) mà client đợi để kết nối
      minimum-idle: 2 #số kết nối tối thiểu mà pool luôn giữ trong trạng thái rảnh (idle)
      maximum-pool-size: 20 #số lượng tối đa mà pool có thể quản lý
      idle-timeout: 10000 #thời gian tối đa mà connection idle(không sử dụng) sẽ được giữ trước khi bị loại bỏ
      max-lifetime: 30000 #thời gian tối đa mà một connection được phép tồn tại trước khi bị loại bỏ, bất kể có đang được sử dụng hay không
      auto-commit: true #các thay đổi trong giao dịch sẽ đuợc tự động commit sau mỗi câu lệnh
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 6000 #thời gian chờ kết nối Redis (miliseconds)
    lettuce:
      pool: #cấu hình connection pool khi dùng Redis client Lettuce
        max-active: 10 #số lượng kết nối tối đa có thể hoạt động đồng thời
        max-idle: 5 #tối đa kết nối rảnh được giữ lại trong pool
        min-idle: 1 #Số lượng kết nối rảnh tối thiểu
        max-wait: 1000ms #thời gian chờ tối đa khi không có kết nối sẵn
  schedule:
    job:
      friend-cache: 0 0 3 * * *
